// Glycolysis — 10 canonical steps, cytosol. Linear with a triose split.
export default {
  id: "glycolysis",
  name: "Glycolysis",
  subtitle: "Glucose → 2 Pyruvate · net +2 ATP, +2 NADH",
  compartment: "Cytosol",
  reactomeId: "R-HSA-70171",
  source: { pathway: "Reactome R-HSA-70171", license: "CC BY 4.0" },
  layout: {
    type: "linear",
    order: [
      ["metabolite", "glucose"], ["reaction", "r1"],
      ["metabolite", "g6p"], ["reaction", "r2"],
      ["metabolite", "f6p"], ["reaction", "r3"],
      ["metabolite", "fbp"], ["reaction", "r4"],
      [["metabolite", "dhap", -1], ["metabolite", "g3p", 1]],
      [["reaction", "r5", -1], ["reaction", "r6", 1]],
      ["metabolite", "bpg13", 1], ["reaction", "r7", 1],
      ["metabolite", "pg3", 1], ["reaction", "r8", 1],
      ["metabolite", "pg2", 1], ["reaction", "r9", 1],
      ["metabolite", "pep", 1], ["reaction", "r10", 1],
      ["metabolite", "pyruvate", 1],
    ],
  },
  metabolites: [
    { id: "glucose", name: "Glucose", abbr: "Glucose", carbons: 6, query: "D-glucose", fallbackSmiles: "OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O" },
    { id: "g6p", name: "Glucose 6-phosphate", abbr: "G6P", carbons: 6, query: "glucose-6-phosphate", fallbackSmiles: "OC1OC(COP(O)(O)=O)C(O)C(O)C1O" },
    { id: "f6p", name: "Fructose 6-phosphate", abbr: "F6P", carbons: 6, query: "fructose-6-phosphate", fallbackSmiles: "OCC1(O)OC(COP(O)(O)=O)C(O)C1O" },
    { id: "fbp", name: "Fructose 1,6-bisphosphate", abbr: "F1,6BP", carbons: 6, query: "fructose-1,6-bisphosphate", fallbackSmiles: "O=P(O)(O)OCC1(O)OC(COP(O)(O)=O)C(O)C1O" },
    { id: "dhap", name: "Dihydroxyacetone phosphate", abbr: "DHAP", carbons: 3, query: "dihydroxyacetone phosphate", fallbackSmiles: "OCC(=O)COP(O)(O)=O" },
    { id: "g3p", name: "Glyceraldehyde 3-phosphate", abbr: "G3P", carbons: 3, query: "glyceraldehyde-3-phosphate", fallbackSmiles: "O=C[C@@H](O)COP(O)(O)=O" },
    { id: "bpg13", name: "1,3-Bisphosphoglycerate", abbr: "1,3-BPG", carbons: 3, query: "1,3-bisphosphoglyceric acid", fallbackSmiles: "O=C(OP(O)(O)=O)[C@@H](O)COP(O)(O)=O" },
    { id: "pg3", name: "3-Phosphoglycerate", abbr: "3-PG", carbons: 3, query: "3-phosphoglyceric acid", fallbackSmiles: "OC(=O)[C@@H](O)COP(O)(O)=O" },
    { id: "pg2", name: "2-Phosphoglycerate", abbr: "2-PG", carbons: 3, query: "2-phosphoglyceric acid", fallbackSmiles: "OC(=O)[C@H](OP(O)(O)=O)CO" },
    { id: "pep", name: "Phosphoenolpyruvate", abbr: "PEP", carbons: 3, query: "phosphoenolpyruvate", fallbackSmiles: "OC(=O)C(=C)OP(O)(O)=O" },
    { id: "pyruvate", name: "Pyruvate", abbr: "Pyruvate", carbons: 3, query: "pyruvic acid", fallbackSmiles: "CC(=O)C(O)=O" },
  ],
  reactions: [
    { id: "r1", enzyme: "Hexokinase", ec: "2.7.1.1", gene: "HK1", reactomeId: "R-HSA-70420", substrates: ["glucose"], products: ["g6p"], consumes: ["ATP"], produces: ["ADP"], deltaATP: -1, deltaNADH: 0, multiplicity: 1, note: "Traps glucose in the cell by adding a charged phosphate it cannot cross the membrane with. First of two priming steps that spend ATP." },
    { id: "r2", enzyme: "Phosphoglucose isomerase", ec: "5.3.1.9", gene: "GPI", reactomeId: "R-HSA-70467", substrates: ["g6p"], products: ["f6p"], deltaATP: 0, deltaNADH: 0, multiplicity: 1, note: "Converts an aldose to a ketose, repositioning the carbonyl so the next phosphorylation can happen at C1." },
    { id: "r3", enzyme: "Phosphofructokinase-1", ec: "2.7.1.11", gene: "PFKL", reactomeId: "R-HSA-70471", substrates: ["f6p"], products: ["fbp"], consumes: ["ATP"], produces: ["ADP"], deltaATP: -1, deltaNADH: 0, multiplicity: 1, note: "The committed, rate-limiting step of glycolysis and the main regulatory valve. Second ATP investment." },
    { id: "r4", enzyme: "Aldolase", ec: "4.1.2.13", gene: "ALDOA", reactomeId: "R-HSA-70486", substrates: ["fbp"], products: ["dhap", "g3p"], deltaATP: 0, deltaNADH: 0, multiplicity: 1, note: "Splits the 6-carbon sugar into two 3-carbon pieces. From here everything downstream happens twice per glucose." },
    { id: "r5", enzyme: "Triosephosphate isomerase", ec: "5.3.1.1", gene: "TPI1", reactomeId: "R-HSA-70494", substrates: ["dhap"], products: ["g3p"], deltaATP: 0, deltaNADH: 0, multiplicity: 1, note: "Converts DHAP into a second G3P so both halves of the sugar continue down the pathway. Near-catalytically-perfect enzyme." },
    { id: "r6", enzyme: "Glyceraldehyde-3-phosphate dehydrogenase", ec: "1.2.1.12", gene: "GAPDH", reactomeId: "R-HSA-70496", substrates: ["g3p"], products: ["bpg13"], consumes: ["NAD+", "Pi"], produces: ["NADH"], deltaATP: 0, deltaNADH: 1, multiplicity: 2, note: "The pay-off phase begins. Oxidises G3P and captures the energy as NADH plus a high-energy phosphate bond. Runs twice per glucose." },
    { id: "r7", enzyme: "Phosphoglycerate kinase", ec: "2.7.2.3", gene: "PGK1", reactomeId: "R-HSA-70501", substrates: ["bpg13"], products: ["pg3"], consumes: ["ADP"], produces: ["ATP"], deltaATP: 1, deltaNADH: 0, multiplicity: 2, note: "First ATP-generating step (substrate-level phosphorylation). Two ATP recovered here per glucose." },
    { id: "r8", enzyme: "Phosphoglycerate mutase", ec: "5.4.2.11", gene: "PGAM1", reactomeId: "R-HSA-70508", substrates: ["pg3"], products: ["pg2"], deltaATP: 0, deltaNADH: 0, multiplicity: 2, note: "Relocates the phosphate from C3 to C2 to set up the next high-energy intermediate." },
    { id: "r9", enzyme: "Enolase", ec: "4.2.1.11", gene: "ENO1", reactomeId: "R-HSA-70505", substrates: ["pg2"], products: ["pep"], produces: ["H2O"], deltaATP: 0, deltaNADH: 0, multiplicity: 2, note: "Removes water to create phosphoenolpyruvate, whose phosphate bond is one of the highest-energy in metabolism." },
    { id: "r10", enzyme: "Pyruvate kinase", ec: "2.7.1.40", gene: "PKM", reactomeId: "R-HSA-70511", substrates: ["pep"], products: ["pyruvate"], consumes: ["ADP"], produces: ["ATP"], deltaATP: 1, deltaNADH: 0, multiplicity: 2, note: "Final, irreversible step. Second ATP-generating reaction; two more ATP per glucose. Net yield of glycolysis is +2 ATP and +2 NADH." },
  ],
  diseases: [
    { id: "pk-def", name: "Pyruvate kinase deficiency", reactionId: "r10", enzyme: "Pyruvate kinase", summary: "The most common enzyme defect of glycolysis. Red blood cells cannot make enough ATP and lyse, causing chronic hemolytic anemia." },
  ],
};
